### ISSUE TITLE
Typescript instructions are incorrect wrt remote vs local audio files

### ISSUE THREAD

**Issue by jeffgca** [AssemblyAI/assemblyai-node-sdk#66]
For this page in the docs:

https://www.assemblyai.com/docs/getting-started/transcribe-an-audio-file

It says:

> If you already have an audio file on your computer, you can also specify a local path, for example ./5_common_sports_injuries.mp3.

This fails with this error message:

```
Error: Transcript creation error, audio_url should start with http
    at TranscriptService.fetch (file:///Users/jeff/code/projects/little-bear/assembly/node_modules/assemblyai/dist/node.mjs:95:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TranscriptService.fetchJson (file:///Users/jeff/code/projects/little-bear/assembly/node_modules/assemblyai/dist/node.mjs:103:26)
    at async TranscriptService.submit (file:///Users/jeff/code/projects/little-bear/assembly/node_modules/assemblyai/dist/node.mjs:498:22)
    at async TranscriptService.transcribe (file:///Users/jeff/code/projects/little-bear/assembly/node_modules/assemblyai/dist/node.mjs:460:28)
    at async run (file:///Users/jeff/code/projects/little-bear/assembly/id_speakers.js:25:22)
```

My code:

```javascript
// Start by making sure the `assemblyai` package is installed.
// If not, you can install it by running the following command:
// npm install assemblyai

import { AssemblyAI } from "assemblyai";

const client = new AssemblyAI({
  apiKey: "***",
});

// const FILE_URL = "https://storage.googleapis.com/aai-web-samples/5_common_sports_injuries.mp3";

const FILE_URL = "./demo.mp3";

// You can also transcribe a local file by passing in a file path
// const FILE_URL = "./path/to/file.mp3";

// Request parameters where speaker_labels has been enabled
const data = {
  audio_url: FILE_URL,
  speaker_labels: true,
};

const run = async () => {
  const transcript = await client.transcripts.transcribe(data);
  console.log(transcript.text);

  // for (let utterance of transcript.utterances) {
  //   console.log(`Speaker ${utterance.speaker}: ${utterance.text}`);
  // }
};

run();

```

**Comment by Swimburger** [comment]
Hi @jeffgca, I removed your API key from the code you shared here.
Make sure to reset your API key in [the dashboard](https://www.assemblyai.com/app/account) so the old key which is now compromised, stops working.

**Comment by Swimburger** [comment]
When you use `audio_url`, the configured string is taken as is and no pre-processing is done to it.
However, you can use the `audio` option which accepts file paths, URLs, buffers, streams, and data-URLs.

**Comment by jeffgca** [comment]
> When you use `audio_url`, the configured string is taken as is and no pre-processing is done to it. However, you can use the `audio` option which accepts file paths, URLs, buffers, streams, and data-URLs.

Thanks for replying so quickly, and sorry about the api key.

This is the boilerplate code from the onboarding process:

```javascript
// Start by making sure the `assemblyai` package is installed.
// If not, you can install it by running the following command:
// npm install assemblyai

import { AssemblyAI } from 'assemblyai';

const client = new AssemblyAI({
  apiKey: 'cc8029efd1514a36bf0d36c0779866c6',
});

const FILE_URL =
  'https://storage.googleapis.com/aai-web-samples/5_common_sports_injuries.mp3';

// You can also transcribe a local file by passing in a file path
// const FILE_URL = './path/to/file.mp3';

// Request parameters where speaker_labels has been enabled
const data = {
  audio_url: FILE_URL,
  speaker_labels: true
}

const run = async () => {
  const transcript = await client.transcripts.transcribe(data);
  console.log(transcript.text);

  for (let utterance of transcript.utterances) {
    console.log(`Speaker ${utterance.speaker}: ${utterance.text}`);
  }
};

run();

```

You should probably expand this boilerplate code to mention that, maybe something like:

```javascript
// Start by making sure the `assemblyai` package is installed.
// If not, you can install it by running the following command:
// npm install assemblyai

import { AssemblyAI } from 'assemblyai';

const client = new AssemblyAI({
  apiKey: 'cc8029efd1514a36bf0d36c0779866c6',
});

const FILE_URL =
  'https://storage.googleapis.com/aai-web-samples/5_common_sports_injuries.mp3';

// Request parameters where speaker_labels has been enabled
const data = {
  audio_url: FILE_URL,
  speaker_labels: true
}

// You can also transcribe a local file by passing in a file path
// const FILE_PATH = './path/to/file.mp3';
// const data = {
//    audio: FILE_PATH,
//    speaker_labels: true
// }

const run = async () => {
  const transcript = await client.transcripts.transcribe(data);
  console.log(transcript.text);

  for (let utterance of transcript.utterances) {
    console.log(`Speaker ${utterance.speaker}: ${utterance.text}`);
  }
};

run();

```

**Comment by Swimburger** [comment]
Thank you for catching that! I'll update the onboarding scripts and get back to you.
